export const PUBLIC_DPRK_SITE_CATALOG = [
  {
    id: "kim-il-sung-university",
    name: "김일성종합대학",
    baseUrl: "http://www.ryongnamsan.edu.kp/",
    languages: ["ko", "en", "zh", "ru"],
    mediaTypes: ["article", "image", "video", "pdf"],
    aliases: ["룡남산", "Kim Il Sung University", "Ryongnamsan"],
  },
  {
    id: "yongsaeng",
    name: "영생",
    baseUrl: "http://yongsaeng.org.kp/",
    languages: ["ko", "en", "zh", "ru"],
    mediaTypes: ["article", "image", "video"],
    aliases: ["김일성김정일기금", "김일성 김정일 기금", "Yongsaeng", "Kim Il Sung-Kim Jong Il Foundation"],
  },
  {
    id: "dprk-portal",
    name: "광야",
    baseUrl: "http://www.dprkportal.kp/",
    languages: ["ko"],
    mediaTypes: ["article", "image"],
    aliases: ["DPRK Portal", "조선민주주의인민공화국 국가망", "북한 사이트 목록"],
  },
  {
    id: "ministry-foreign-affairs",
    name: "조선민주주의인민공화국 외무성",
    baseUrl: "http://www.mfa.gov.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image"],
    aliases: ["외무성", "Ministry of Foreign Affairs DPRK", "MFA DPRK"],
  },
  {
    id: "maritime-administration",
    name: "국가해사감독국",
    baseUrl: "http://www.ma.gov.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "pdf"],
    aliases: ["해사감독국", "Maritime Administration of the DPRK"],
  },
  {
    id: "financial-intelligence-agency",
    name: "금융정보국",
    baseUrl: "http://www.fia.law.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "pdf"],
    aliases: ["금융정보기관", "Financial Intelligence Agency DPRK", "FIA DPRK"],
  },
  {
    id: "pulbora",
    name: "삼흥지적자원교류사",
    baseUrl: "http://www.pulbora.edu.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image"],
    aliases: ["불보라", "Pulbora", "Samhung Intellectual Assets Center"],
  },
  {
    id: "sports-dprk",
    name: "조선민주주의인민공화국 체육",
    baseUrl: "http://www.sdprk.org.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "video"],
    aliases: ["조선체육", "Sports in the DPR Korea", "SDPRK"],
  },
  {
    id: "friend",
    name: "벗",
    baseUrl: "http://www.friend.com.kp/",
    languages: ["ko", "en", "zh", "ru"],
    mediaTypes: ["article", "image"],
    aliases: ["조선대외문화련락위원회", "Friend", "Korean Friendship Association"],
  },
  {
    id: "care-of-aged",
    name: "조선년로자보호련맹",
    baseUrl: "http://www.korelcfund.org.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "pdf"],
    aliases: ["년로자보호련맹", "Korea Federation for Care of the Aged", "Korelcfund"],
  },
  {
    id: "education-fund",
    name: "조선교육후원기금",
    baseUrl: "http://www.koredufund.org.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "pdf"],
    aliases: ["교육후원기금", "Korea Education Fund", "Koredufund"],
  },
  {
    id: "pyongyang-times",
    name: "평양타임스",
    baseUrl: "http://www.pyongyangtimes.com.kp/",
    languages: ["en"],
    mediaTypes: ["article", "image"],
    aliases: ["The Pyongyang Times", "Pyongyang Times"],
  },
  {
    id: "grand-national-unity",
    name: "민족대단결",
    baseUrl: "http://www.gnu.rep.kp/",
    languages: ["ko"],
    mediaTypes: ["article", "image", "broadcast"],
    aliases: ["Grand National Unity", "GNU", "평양방송"],
  },
  {
    id: "social-scientists",
    name: "조선사회과학자협회",
    baseUrl: "http://www.kass.org.kp/",
    languages: ["ko", "en", "zh", "ru", "es", "fr", "de", "ar", "ja"],
    mediaTypes: ["article", "image", "pdf"],
    aliases: ["사회과학자협회", "Korean Association of Social Scientists", "KASS"],
  },
  {
    id: "national-insurance",
    name: "조선민족보험총회사",
    baseUrl: "http://www.knic.com.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "pdf"],
    aliases: ["민족보험총회사", "Korea National Insurance Corporation", "KNIC"],
  },
  {
    id: "international-youth-travel",
    name: "조선국제청소년려행사",
    baseUrl: "http://www.kiyctc.com.kp/",
    languages: ["ko", "en", "zh", "ru"],
    mediaTypes: ["article", "image"],
    aliases: ["국제청소년려행사", "Korea International Youth and Children's Travel Company", "KIYCTC"],
  },
  {
    id: "air-koryo",
    name: "고려항공",
    baseUrl: "http://www.airkoryo.com.kp/",
    languages: ["ko", "en", "zh", "ru"],
    mediaTypes: ["article", "image"],
    aliases: ["Air Koryo", "AirKoryo"],
  },
  {
    id: "korean-cooks",
    name: "조선료리협회",
    baseUrl: "http://www.cooks.org.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "video"],
    aliases: ["조선요리협회", "Korean Cooks Association", "Korean Cookery Association"],
  },
  {
    id: "korean-film",
    name: "조선영화수출입사",
    baseUrl: "http://www.korfilm.com.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "video"],
    aliases: ["조선영화", "Korean Film Export and Import Corporation", "Korfilm"],
  },
  {
    id: "dprk-tourism",
    name: "조선관광",
    baseUrl: "http://www.tourismdprk.gov.kp/",
    languages: ["ko", "en", "zh", "ru"],
    mediaTypes: ["article", "image", "video"],
    aliases: ["DPR Korea Tour", "DPRK Tourism", "국가관광총국"],
  },
  {
    id: "minzu",
    name: "민족",
    baseUrl: "http://www.minzu.rep.kp/",
    languages: ["ko"],
    mediaTypes: ["article", "image"],
    aliases: ["Minzu"],
  },
  {
    id: "foreign-trade",
    name: "조선의 무역",
    baseUrl: "http://www.kftrade.com.kp:8888/",
    languages: ["ko", "en", "zh", "ru"],
    mediaTypes: ["article", "image", "pdf"],
    aliases: ["Foreign Trade of DPRK", "KFTrade", "조선무역"],
  },
  {
    id: "youth-sinmun",
    name: "청년전위",
    baseUrl: "http://www.youth.rep.kp/",
    languages: ["ko"],
    mediaTypes: ["article", "image"],
    aliases: ["청년신문", "Youth Sinmun", "Youth"],
  },
  {
    id: "manmulsang",
    name: "만물상",
    baseUrl: "http://www.manmulsang.com.kp/",
    languages: ["ko", "en", "zh", "ru"],
    mediaTypes: ["article", "image"],
    aliases: ["Manmulsang", "만물상전자상업"],
  },
  {
    id: "kim-chaek-university",
    name: "김책공업종합대학",
    baseUrl: "http://www.kut.edu.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "pdf"],
    aliases: ["김책공대", "Kim Chaek University of Technology", "KUT"],
  },
  {
    id: "grand-peoples-study-house",
    name: "인민대학습당",
    baseUrl: "http://www.gpsh.edu.kp:8080/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "pdf"],
    aliases: ["Grand People's Study House", "GPSH"],
  },
  {
    id: "samhae-insurance",
    name: "삼해보험회사",
    baseUrl: "http://www.samhae.com.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "pdf"],
    aliases: ["삼해보험", "Samhae Insurance Company", "Samhae"],
  },
  {
    id: "polestar-insurance",
    name: "북극성보험회사",
    baseUrl: "http://www.polestar.com.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "pdf"],
    aliases: ["북극성보험", "Polestar Insurance Company", "Polestar"],
  },
  {
    id: "science-technology-commission",
    name: "국가과학기술위원회",
    baseUrl: "http://www.mirae.aca.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "pdf"],
    aliases: ["미래", "State Commission of Science and Technology", "Mirae"],
  },
  {
    id: "ministry-public-health",
    name: "보건성",
    baseUrl: "http://www.moph.gov.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "pdf"],
    aliases: ["조선민주주의인민공화국 보건성", "Ministry of Public Health DPRK", "MOPH"],
  },
  {
    id: "korean-art",
    name: "조선예술",
    baseUrl: "http://www.korart.sca.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "video"],
    aliases: ["Korean Art", "Korart"],
  },
  {
    id: "ryomyong-education",
    name: "려명",
    baseUrl: "http://www.ryomyong.edu.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "pdf"],
    aliases: ["Ryomyong", "려명교육"],
  },
  {
    id: "korean-stamp",
    name: "조선우표사",
    baseUrl: "http://www.korstamp.com.kp/",
    languages: ["ko", "en", "zh", "ru"],
    mediaTypes: ["article", "image"],
    aliases: ["조선우표", "Korea Stamp Corporation", "Korstamp"],
  },
];

export const PUBLIC_DPRK_SITE_HOSTS = [...new Set(PUBLIC_DPRK_SITE_CATALOG
  .map((source) => {
    try {
      return new URL(source.baseUrl).hostname.toLocaleLowerCase("en-US");
    } catch {
      return "";
    }
  })
  .filter(Boolean))];
