const OFFICIAL_SITE_CRAWL_BUDGET = {
  limitPerSource: 160,
  maxLinksPerSource: 800,
  maxDiscoveryPages: 100,
  maxSourceMs: 240000,
  requestDelayMs: 400,
  discoveryReserveMs: 70000,
};

export const SEARCH_SOURCES = [
  {
    id: "rodong-sinmun",
    name: "로동신문",
    sourceType: "official_site",
    baseUrl: "http://www.rodong.rep.kp/",
    languages: ["ko"],
    mediaTypes: ["article", "image"],
    aliases: ["노동신문", "Rodong Sinmun", "Rodong"],
    crawler: {
      enabled: true,
      importer: "official-sites",
      entryUrl: "http://www.rodong.rep.kp/",
      strategy: "official-html-crawl",
      indexEntryUrl: false,
      indexListingFallbacks: true,
      preferReadable: true,
      cacheFirstReadable: true,
      ...OFFICIAL_SITE_CRAWL_BUDGET,
      limitPerSource: 220,
      maxLinksPerSource: 360,
      maxDiscoveryPages: 24,
      maxSourceMs: 600000,
      maxDetailFetchesPerSource: 220,
      maxBodyLength: 14000,
      requestDelayMs: 1200,
      generatedListingPages: 80,
      listingSections: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      searchUrlTemplates: [
        "http://www.rodong.rep.kp/ko/index.php?{query}",
      ],
      searchQueryEncoding: "rodong-search-base64",
      searchPreferReadable: true,
      indexSearchResults: true,
      fetchSearchResultPages: true,
      searchQueries: [
        "원산갈마해안관광지구 준공식",
        "원산갈마",
        "원산",
      ],
      detailSeedUrls: [
        {
          url: "http://www.rodong.rep.kp/ko/index.php?OEAyMDI1LTA3LTAyLTAxOEAxOUBA7JuQ7IKw6rCI66eIQDExMDY==",
          title: "원산갈마해안관광지구에서 봉사 시작",
          date: "2025-07-02",
        },
        {
          url: "http://www.rodong.rep.kp/ko/index.php?OEAyMDI1LTA3LTAzLTA0NUAxOUBA7JuQ7IKw6rCI66eIQDExMDU==",
          title: "인민의 웃음소리 끝없이 울려퍼지는 동해의 명사십리 원산갈마해안관광지구에서",
          date: "2025-07-03",
        },
        {
          url: "http://www.rodong.rep.kp/ko/index.php?OEAyMDI1LTA3LTMxLTA4MUAxOUBA7JuQ7IKw6rCI66eIQDE4OQ==",
          title: "[수필] 준공테프",
          date: "2025-07-31",
        },
        {
          url: "http://www.rodong.rep.kp/ko/index.php?OEAyMDI1LTA4LTEzLTAyMkAxOUBA7JuQ7IKw6rCI66eIQDE4Mg==",
          title: "혁명학원 원아들이 원산갈마해안관광지구에서 즐거운 나날을 보내였다",
          date: "2025-08-13",
        },
        {
          url: "http://www.rodong.rep.kp/ko/index.php?OEAyMDI1LTA5LTE4LTA2NkAxOUBA7JuQ7IKw6rCI66eIQDE2Ng==",
          title: "원산갈마해안관광지구에서 미술기념품전시회 개막",
          date: "2025-09-18",
        },
      ],
      discoverUrlPatterns: ["index.php?MUBA"],
      includeUrlPatterns: ["index.php?MTJ", /\/ko\/index\.php\?OEA/i],
      schedule: "daily",
      robotsPolicy: "respect",
      selectors: {
        title: "h1, h2, h3, title",
        date: "time, .date, [class*=date]",
        body: "article, main, .article, .content, body",
      },
    },
  },
  {
    id: "kcna",
    name: "조선중앙통신",
    sourceType: "official_site",
    baseUrl: "http://www.kcna.kp/",
    languages: ["ko", "en", "ja", "zh", "ru", "es"],
    mediaTypes: ["article", "image"],
    aliases: ["KCNA", "Korean Central News Agency", "조선중앙통신사"],
    crawler: {
      enabled: true,
      importer: "official-sites",
      entryUrl: "http://www.kcna.kp/kp",
      seedUrls: [
        "http://www.kcna.kp/kp/category/articles/q/54c0ca4ca013a92cc9cf95bd4004c61a.kcmsf?page=16",
        "http://www.kcna.kp/kp/category/articles/q/5394b80bdae203fadef02522cfb578c0.kcmsf?page=33",
        "http://www.kcna.kp/en",
        "http://www.kcna.kp/jp",
        "http://www.kcna.kp/cn",
        "http://www.kcna.kp/ru",
        "http://www.kcna.kp/sp",
        "http://www.kcna.kp/es",
      ],
      detailSeedUrls: [
        {
          url: "http://www.kcna.kp/kp/article/q/7814962e12328ec63931b157c5b3d5ceae3d0eb9cfe8dcd1cfb706a70acfaa0f2a339be80aceaeaf7192c1713ecd8235.kcmsf",
          title: "원산갈마해안관광지구에서 봉사 시작",
          date: "2025-07-02",
        },
      ],
      strategy: "official-html-crawl",
      indexEntryUrl: false,
      indexListingFallbacks: true,
      preferReadable: true,
      preferSeedUrls: true,
      ...OFFICIAL_SITE_CRAWL_BUDGET,
      limitPerSource: 260,
      maxLinksPerSource: 420,
      maxDiscoveryPages: 30,
      maxSourceMs: 480000,
      maxDetailFetchesPerSource: 260,
      discoverUrlPatterns: [/\/(?:kp|en|jp|cn|ru|sp|es)\/category\/articles/i],
      includeUrlPatterns: [/\/(?:kp|en|jp|cn|ru|sp|es)\/article\/q\//i],
      schedule: "daily",
      robotsPolicy: "respect",
      selectors: {
        title: "h1, h2, h3, title",
        date: "time, .date, [class*=date]",
        body: "article, main, .news, .content, body",
      },
    },
  },
  {
    id: "voice-of-korea",
    name: "조선의 소리",
    sourceType: "official_site",
    baseUrl: "http://www.vok.rep.kp/",
    languages: ["ko", "en", "ja", "zh", "ru", "es", "fr", "ar", "de"],
    mediaTypes: ["article", "broadcast"],
    aliases: ["Voice of Korea", "VOK", "조선의소리"],
    crawler: {
      enabled: true,
      importer: "official-sites",
      entryUrl: "http://www.vok.rep.kp/index.php/Colist/newslist/18/ko",
      seedUrls: [
        "http://www.vok.rep.kp/index.php/Colist/newslist/18/ko",
        "http://www.vok.rep.kp/index.php/Colist/newslist/18/en",
        "http://www.vok.rep.kp/index.php/Colist/newslist/18/ru",
        "http://www.vok.rep.kp/index.php/Colist/revolist/36/sp",
        "http://www.vok.rep.kp/index.php/Colist/revolist/36/ge",
        "http://www.vok.rep.kp/index.php/Colist/revolist/36/fr",
        "http://www.vok.rep.kp/index.php/Colist/revolist/36/cn",
        "http://www.vok.rep.kp/index.php/Colist/revolist/36/ja",
        "http://www.vok.rep.kp/index.php/Colist/revolist/36/ar",
        "http://www.vok.rep.kp/index.php/Colist/newslist/18/ar",
        "http://www.vok.rep.kp/index.php/Colist/newslist/18/cn",
        "http://www.vok.rep.kp/index.php/Colist/newslist1/48/jp",
        "http://www.vok.rep.kp/index.php/Colist/newslist1/48/ko",
        "http://www.vok.rep.kp/index.php/Colist/newslist1/48/en",
        "http://www.vok.rep.kp/index.php/Colist/newslist1/48/ru",
        "http://www.vok.rep.kp/index.php/Colist/revolist/36/ko",
        "http://www.vok.rep.kp/index.php/Colist/revolist/36/en",
        "http://www.vok.rep.kp/index.php/Colist/plist/57/ko",
        "http://www.vok.rep.kp/index.php/Colist/pclist/57/1/ko",
        "http://www.vok.rep.kp/index.php/Colist/pclist/57/2/ko",
        "http://www.vok.rep.kp/index.php/Colist/pclist/57/3/ko",
        "http://www.vok.rep.kp/index.php/Colist/cscdlist/69/6/ko",
        "http://www.vok.rep.kp/index.php/Colist/cscdlist/69/7/ko",
        "http://www.vok.rep.kp/index.php/Colist/cscdlist/69/8/ko",
        "http://www.vok.rep.kp/index.php/Colist/cscdlist/69/9/ko",
        "http://www.vok.rep.kp/index.php/Colist/cscdlist/69/10/ko",
        "http://www.vok.rep.kp/index.php/Colist/vsqlist/87/ko",
        "http://www.vok.rep.kp/index.php/Colist/vscdlist/87/14/ko",
        "http://www.vok.rep.kp/index.php/Colist/vscdlist/87/15/ko",
        "http://www.vok.rep.kp/index.php/Colist/vscdlist/87/16/ko",
        "http://www.vok.rep.kp/index.php/Colist/vscdlist/87/17/ko",
        "http://www.vok.rep.kp/index.php/Colist/vscdlist/87/18/ko",
        "http://www.vok.rep.kp/index.php/Colist/holist/94/ko",
        "http://www.vok.rep.kp/index.php/Colist/holist/95/ko",
        "http://www.vok.rep.kp/index.php/Colist/holist/96/ko",
      ],
      detailSeedUrls: [
        {
          url: "http://www.vok.rep.kp/index.php/revo_de/getDetail/ikn250625008/ko",
          title: "사회주의문명개화의 새 경관을 펼친 동해기슭의 관광명소 원산갈마해안관광지구 준공식 성대히 진행",
          date: "2025-06-26",
        },
        {
          url: "http://www.vok.rep.kp/index.php/revo_de/getDetail/ien250625008/en",
          title: "Inaugural Ceremony of Wonsan Kalma Coastal Tourist Area Held with Splendour",
          date: "2025-06-26",
        },
      ],
      strategy: "official-html-crawl",
      indexEntryUrl: false,
      indexListingFallbacks: true,
      preferListingDocuments: false,
      preferReadable: true,
      cacheFirstReadable: true,
      preferSeedUrls: true,
      ...OFFICIAL_SITE_CRAWL_BUDGET,
      limitPerSource: 320,
      timeoutMs: 11000,
      maxLinksPerSource: 520,
      maxDiscoveryPages: 40,
      maxSourceMs: 600000,
      maxDetailFetchesPerSource: 240,
      maxLinksPerDiscoveryPage: 220,
      requestDelayMs: 500,
      discoverUrlPatterns: ["/index.php/Colist/"],
      includeUrlPatterns: [
        "/index.php/revo_de/getDetail/",
        "/index.php/detail_com/",
      ],
      schedule: "daily",
      robotsPolicy: "respect",
      selectors: {
        title: "h1, h2, h3, title",
        date: "time, .date, [class*=date]",
        body: "article, main, .content, body",
      },
    },
  },
  {
    id: "minju-choson",
    name: "민주조선",
    sourceType: "official_site",
    baseUrl: "http://www.minju.rep.kp/",
    languages: ["ko"],
    mediaTypes: ["article", "image"],
    aliases: ["Minju Choson", "Minju Joson"],
    crawler: {
      enabled: true,
      importer: "official-sites",
      entryUrl: "http://www.minju.rep.kp/",
      strategy: "official-html-crawl",
      indexEntryUrl: false,
      indexListingFallbacks: true,
      preferListingDocuments: true,
      preferReadable: true,
      ...OFFICIAL_SITE_CRAWL_BUDGET,
      maxDiscoveryPages: 12,
      discoverUrlPatterns: [/\/home\/index\/(?:first|revolution|power_news|all_view|politics|economy|culture|tourist|overseas|international|history|photos|video)\/\d+\/ko$/i],
      includeUrlPatterns: [/\/Home\/index\/disp\/\d+\/ko$/i, /\/uploads\/photo\/\d{4}\/\d{2}\/[^?#]+\.(?:png|jpe?g|webp)$/i],
      excludeUrlPatterns: ["/Home/index/first/", "/home/index/first/", "/Home/index/all_view/", "/home/index/all_view/"],
      schedule: "daily",
      robotsPolicy: "respect",
      selectors: {
        title: "h1, h2, h3, title",
        date: "time, .date, [class*=date]",
        body: "article, main, .content, body",
      },
    },
  },
  {
    id: "ryugyong",
    name: "류경",
    sourceType: "official_site",
    baseUrl: "https://www.mediaryugyong.com.kp/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "image", "video"],
    aliases: ["Ryugyong", "Media Ryugyong", "류경"],
    crawler: {
      enabled: true,
      importer: "official-sites",
      entryUrl: "http://www.mediaryugyong.com.kp/",
      seedUrls: [
        "http://www.mediaryugyong.com.kp/photo?lang=ko&page=1",
        "http://www.mediaryugyong.com.kp/photo?lang=ko&page=2",
        "http://www.mediaryugyong.com.kp/photo?lang=en&page=1",
        "http://www.mediaryugyong.com.kp/photo?lang=en&page=2",
        "http://www.mediaryugyong.com.kp/movie?lang=ko&page=1",
        "http://www.mediaryugyong.com.kp/movie?lang=en&page=1",
      ],
      strategy: "official-html-crawl",
      indexEntryUrl: false,
      preferSeedUrls: true,
      preferReadable: true,
      ...OFFICIAL_SITE_CRAWL_BUDGET,
      limitPerSource: 360,
      maxLinksPerSource: 520,
      maxDiscoveryPages: 90,
      generatedListingPages: 35,
      listingSections: ["photo", "movie"],
      listingLanguages: ["ko", "en"],
      discoverUrlPatterns: [/\/(?:photo|movie)\?lang=(?:ko|en)&page=\d+$/i],
      includeUrlPatterns: ["/contents/photo/", "/contents/video/"],
      schedule: "daily",
      robotsPolicy: "respect",
      selectors: {
        title: "h1, h2, h3, title",
        date: "time, .date, [class*=date]",
        body: "article, main, .content, body",
      },
    },
  },
  {
    id: "naenara",
    name: "내나라",
    sourceType: "official_site",
    baseUrl: "http://www.naenara.com.kp/",
    languages: ["ko", "en", "ja", "zh", "ru", "es", "fr", "de", "ar"],
    mediaTypes: ["article", "image", "pdf"],
    aliases: ["Naenara", "내나라"],
    crawler: {
      enabled: true,
      importer: "official-sites",
      entryUrl: "http://www.naenara.com.kp/",
      seedUrls: [
        "http://www.naenara.com.kp/main/index/ko/news",
        "http://www.naenara.com.kp/main/index/en/news",
        "http://www.naenara.com.kp/main/index/ko/tourism",
        "http://www.naenara.com.kp/main/index/en/tourism",
        "http://www.naenara.com.kp/main/index/ko/first",
        "http://www.naenara.com.kp/main/index/en/first",
        "http://www.naenara.com.kp/main/index/fr/tourism",
        "http://www.naenara.com.kp/main/index/sp/tourism",
        "http://www.naenara.com.kp/main/index/ge/tourism",
        "http://www.naenara.com.kp/main/index/ru/tourism",
        "http://www.naenara.com.kp/main/index/ch/tourism",
        "http://www.naenara.com.kp/main/index/ja/tourism",
        "http://www.naenara.com.kp/main/index/ar/tourism",
        "http://www.naenara.com.kp/main/index/fr/first",
        "http://www.naenara.com.kp/main/index/sp/first",
        "http://www.naenara.com.kp/main/index/ge/first",
        "http://www.naenara.com.kp/main/index/ru/first",
        "http://www.naenara.com.kp/main/index/ch/first",
        "http://www.naenara.com.kp/main/index/ja/first",
        "http://www.naenara.com.kp/main/index/ar/first",
      ],
      strategy: "official-html-crawl",
      indexEntryUrl: false,
      preferSeedUrls: true,
      preferReadable: true,
      ...OFFICIAL_SITE_CRAWL_BUDGET,
      maxLinksPerSource: 320,
      maxDiscoveryPages: 24,
      discoverUrlPatterns: [
        /\/main\/index\/(?:ko|en)\/(?:news|first|tourism)(?:$|[?#])/i,
        /\/main\/index\/(?:fr|sp|ge|ru|ch|ja|ar)\/(?:first|tourism)(?:$|[?#])/i,
      ],
      includeUrlPatterns: ["/main/detail/", "/main/getDetail/", "/main/content/"],
      excludeUrlPatterns: ["/main/index/ko/"],
      schedule: "daily",
      robotsPolicy: "respect",
      selectors: {
        title: "h1, h2, h3, title",
        date: "time, .date, [class*=date]",
        body: "article, main, .content, body",
      },
    },
  },
  {
    id: "choson-sinbo",
    name: "조선신보",
    sourceType: "archive",
    baseUrl: "https://www.chosonsinbo.com/",
    languages: ["ko", "ja"],
    mediaTypes: ["article", "image"],
    aliases: ["Choson Sinbo", "조선신보"],
    crawler: {
      enabled: true,
      importer: "official-sites",
      entryUrl: "https://www.chosonsinbo.com/",
      wordpressPostsUrl: "https://www.chosonsinbo.com/wp-json/wp/v2/posts?per_page=50&_embed=wp:featuredmedia&_fields=id,date,modified,link,title,excerpt,content,_embedded.wp:featuredmedia.source_url,_embedded.wp:featuredmedia.media_details",
      wordpressSearchUrlTemplate: "https://www.chosonsinbo.com/wp-json/wp/v2/posts?per_page=50&search={query}&_embed=wp:featuredmedia&_fields=id,date,modified,link,title,excerpt,content,_embedded.wp:featuredmedia.source_url,_embedded.wp:featuredmedia.media_details",
      wordpressSearchQueries: [
        "원산갈마해안관광지구 준공식",
        "원산갈마 준공식",
        "원산갈마",
        "Wonsan Kalma",
        "사회주의문명개화의 새 경관",
      ],
      wordpressPreferReadable: true,
      wordpressFetchDetailPages: false,
      skipHtmlDiscovery: true,
      minBodyLength: 80,
      strategy: "official-html-crawl",
      indexEntryUrl: false,
      preserveOnFailure: false,
      ...OFFICIAL_SITE_CRAWL_BUDGET,
      includeUrlPatterns: [/^https?:\/\/(?:www\.)?chosonsinbo\.com\/(?:jp\/)?20\d{2}\/\d{2}\//i],
      excludeUrlPatterns: ["/category/", "/tag/", "/page/", "/contact/", "/privacy-policy/", "/order/", "/wp-content/"],
      schedule: "daily",
      robotsPolicy: "respect",
      selectors: {
        title: "h1, h2, h3, title",
        date: "time, .date, [class*=date]",
        body: "article, main, .entry-content, .content, body",
      },
    },
  },
  {
    id: "korean-books",
    name: "조선의 출판물",
    sourceType: "official_site",
    baseUrl: "http://www.korean-books.com.kp/",
    languages: ["ko", "en", "ja", "zh", "ru"],
    mediaTypes: ["pdf"],
    aliases: ["Korean Books", "Korean Publications", "조선출판물"],
    crawler: {
      enabled: true,
      importer: "official-sites",
      entryUrl: "http://www.korean-books.com.kp/",
      seedUrls: [
        "http://www.korean-books.com.kp/index.php/Main/index/total/ko",
        "http://www.korean-books.com.kp/index.php/Main/index/work/ko",
        "http://www.korean-books.com.kp/index.php/Main/index/periodic/ko",
        "http://www.korean-books.com.kp/index.php/Main/index/book/ko",
        "http://www.korean-books.com.kp/index.php/Main/index/album/ko",
        "http://www.korean-books.com.kp/index.php/Main/index/etc/ko",
        "http://www.korean-books.com.kp/index.php/Main/periodic/ko/pictorialkorea",
        "http://www.korean-books.com.kp/index.php/Main/periodic/ko/mountainkorea",
        "http://www.korean-books.com.kp/index.php/Main/periodic/ko/tradekorea",
      ],
      strategy: "official-html-crawl",
      preferSeedUrls: true,
      detailSeedUrls: [
        {
          url: "http://www.korean-books.com.kp/KBMbooks/ko/etc/cahier/20250703115805.pdf",
          title: "원산갈마해안관광지구안내",
          date: "2025-07-03",
        },
        {
          url: "http://www.korean-books.com.kp/KBMbooks/ko/etc/post/20260413105243.pdf",
          title: "원산갈마해안관광지구",
          date: "2026-04-13",
        },
        {
          url: "http://www.korean-books.com.kp/KBMbooks/ko/work/leader1/1032.pdf",
          title: "강원도를 국제관광지로 잘 꾸릴데 대하여",
          date: "2026-05-21",
        },
      ],
      preferReadable: true,
      cacheFirstReadable: true,
      fetchPdfText: true,
      indexEntryUrl: false,
      ...OFFICIAL_SITE_CRAWL_BUDGET,
      maxDiscoveryPages: 16,
      maxPdfTextFetchesPerSource: 8,
      maxPdfTextLength: 9000,
      discoverUrlPatterns: [
        /\/index\.php\/Main\/index\/(?:total|work|periodic|book|album|etc)\/ko\/?$/i,
        /\/index\.php\/Main\/periodic\/ko\/(?:pictorialkorea|mountainkorea|tradekorea)\/?$/i,
      ],
      includeUrlPatterns: [".pdf"],
      schedule: "daily",
      robotsPolicy: "respect",
      selectors: {
        title: "h1, h2, h3, title",
        date: "time, .date, [class*=date]",
        body: "article, main, .content, body",
      },
    },
  },
  {
    id: "kcna-watch",
    name: "KCNA Watch",
    sourceType: "archive",
    baseUrl: "https://kcnawatch.org/",
    languages: ["ko", "en"],
    mediaTypes: ["article", "pdf", "image", "video"],
    aliases: ["KCNA Watch", "조선중앙통신 아카이브", "Korean Central News Agency"],
    crawler: {
      enabled: true,
      importer: "kcna-watch",
      entryUrl: "https://kcnawatch.org/",
      feedUrl: "https://kcnawatch.org/feed/",
      detailSeedUrls: [
        {
          url: "https://kcnawatch.org/newstream/1750885366-665971553/tourist-attraction-on-east-coast-showing-new-scenery-of-inflorescence-of-socialist-civilizationinaugural-ceremony-of-wonsan-kalma-coastal-tourist-area-held-with-splendour/",
          date: "2025-06-26",
        },
      ],
      searchUrlTemplates: [
        "https://kcnawatch.org/?s={query}",
      ],
      searchPreferReadable: true,
      indexSearchResults: true,
      fetchSearchResultPages: true,
      searchQueries: [
        "원산갈마",
        "원산갈마해안관광지구",
        "갈마해안관광지구",
        "갈마반도",
        "Wonsan Kalma",
        "Wonsan Kalma Coastal Tourist Area",
        "Kalma Coastal Tourist Area",
        "최현",
        "Choe Hyon",
        "화성",
        "Hwasong",
        "김정은",
        "Kim Jong Un",
        "평양",
        "Pyongyang",
      ],
      sitemapUrls: [
        "https://kcnawatch.org/sitemap_index.xml",
      ],
      maxSitemaps: 8,
      strategy: "archive-html-crawl",
      indexEntryUrl: false,
      maxDetailFetchesPerSource: 80,
      includeUrlPatterns: ["/newstream/"],
      excludeUrlPatterns: [/\/newstream\/?$/i, "/category/", "/tag/", "/page/"],
      schedule: "daily",
      robotsPolicy: "respect",
      selectors: {
        title: "h1.entry-title, h1, h2, title",
        date: "time, .date, .entry-date",
        body: "article, .entry-content, main, body",
      },
    },
  },
  {
    id: "koryo-vod",
    name: "고려TV VOD",
    sourceType: "video_archive",
    baseUrl: "https://vod.koryo.tv/",
    languages: ["ko", "en"],
    mediaTypes: ["video"],
    searchTabs: ["all", "video"],
    aliases: ["고려TV", "Koryo TV", "Koryo VOD", "VOD"],
    crawler: {
      enabled: true,
      importer: "koryo-vod",
      entryUrl: "https://vod.koryo.tv/",
      apiUrl: "https://vod.koryo.tv/api/v1/media",
      strategy: "video-json-api",
      indexEntryUrl: false,
      schedule: "daily",
      robotsPolicy: "respect",
      selectors: {
        title: "h1, h2, h3, title",
        date: "time, .date, [class*=date]",
        body: "article, main, .content, body",
      },
    },
  },
  {
    id: "youtube",
    name: "YouTube",
    sourceType: "video_archive",
    baseUrl: "https://www.youtube.com/",
    languages: ["ko", "en", "ja", "zh", "ru", "multi"],
    mediaTypes: ["video"],
    searchTabs: ["all", "video"],
    aliases: ["메아리", "Meari", "YouTube Meari", "supersuhui", "슈퍼수희", "YouTube supersuhui"],
    crawler: {
      enabled: true,
      importer: "youtube-metadata",
      entryUrl: "https://www.youtube.com/",
      strategy: "youtube-rss-search-metadata",
      indexEntryUrl: false,
      schedule: "daily",
      robotsPolicy: "respect",
      searchResultsPerQuery: 3,
      searchCandidateLimitPerQuery: 8,
      searchCandidateConcurrency: 4,
      searchTargetConcurrency: 4,
      searchCandidateTimeoutMs: 5000,
      searchCandidateRetries: 0,
      searchQueries: [
        "원산갈마",
        "원산갈마해안관광지구",
        "화성",
        "화성지구",
        "Hwasong",
        "최현",
        "Choe Hyon",
        "김정은",
        "Kim Jong Un",
        "준공식",
        "현지지도",
      ],
      channels: [
        {
          name: "메아리",
          entryUrl: "https://www.youtube.com/@-meari-",
          channelId: "UC7CdB6acpJKKku-QfZ6QfMw",
          feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UC7CdB6acpJKKku-QfZ6QfMw",
          aliases: ["메아리", "Meari", "YouTube Meari"],
        },
        {
          name: "supersuhui",
          entryUrl: "https://www.youtube.com/@supersuhui",
          channelId: "UCBopKYmbS-Ki6ilhe1mT_nw",
          feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCBopKYmbS-Ki6ilhe1mT_nw",
          aliases: ["supersuhui", "슈퍼수희", "YouTube supersuhui"],
        },
      ],
      seedVideos: [
        {
          url: "https://www.youtube.com/watch?v=UPUkZp6_EXU",
          channelName: "메아리",
          date: "2025-06-26",
          aliases: ["메아리", "Meari", "원산갈마해안관광지구 준공식", "Wonsan Kalma", "Inaugural Ceremony"],
        },
        {
          url: "https://www.youtube.com/watch?v=YMdka8o8mtE",
          channelName: "supersuhui",
          date: "2025-06-26",
          aliases: ["supersuhui", "슈퍼수희", "원산갈마해안관광지구 준공식", "Wonsan Kalma", "Inaugural Ceremony"],
        },
      ],
    },
  },
];

export const SOURCE_ORDER = SEARCH_SOURCES.map((source) => source.name);
export const SOURCE_BY_ID = Object.fromEntries(SEARCH_SOURCES.map((source) => [source.id, source]));
export const SOURCE_ID_BY_NAME = Object.fromEntries(SEARCH_SOURCES.map((source) => [source.name, source.id]));

export const CRAWLER_SOURCE_CONFIG = SEARCH_SOURCES.map((source) => ({
  sourceId: source.id,
  sourceName: source.name,
  sourceType: source.sourceType,
  baseUrl: source.baseUrl,
  mediaTypes: source.mediaTypes,
  searchTabs: source.searchTabs || [],
  crawler: source.crawler,
}));
